/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfacegrafica3.view;

/**
 *
 * @author leleb
 */
public class JanelaCadastroFornecedor extends javax.swing.JInternalFrame {

    private static JanelaCadastroFornecedor instancia;
    private JanelaPrincipal janelaPrincipal;
    
     /**
     * Creates new form JanelaCadastroFornecedor
     * @param janelaPrincipal
     */
    public JanelaCadastroFornecedor(JanelaPrincipal janelaPrincipal) {
        initComponents();
         this.janelaPrincipal = janelaPrincipal;
         txtId.setText("0");
    }
    
    public static JanelaCadastroFornecedor getInstancia(JanelaPrincipal janelaPrincipal){
      if(instancia == null)
          instancia = new JanelaCadastroFornecedor(janelaPrincipal);
      return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Fornecedor");
        setVisible(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
